version: 2.1

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    test:
      jobs:
        - test

orbs:
  node: circleci/node@1.1.6
